...
Ahh... 
+[Are you okay?]
Not really. Look at the state of our farm! Our poor, precious plants... Oh bees, come home please!
Sorry, at times like these I can't help but fall into a deep pit of despair.
It'll be ok though, I trust you detective. But boy oh boy, if I don't see some plants growing soon, I think I'll just cry.
+[Uh... bye.]
What? Oh, bye...