Hiya detective.
Have you been over to the city yet?
There's been loads of roadworks happening lately, they keep saying they're going to finish by the end of the month and then they extend it by another few months...